name: Push the container images

on:
  push:
    branches:
      - main 
    tags:
      - 'v*'

env:
  CONTAINER_REGISTRY: ghcr.io

jobs:
  push_image:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Calculate the version
        run: echo "IMAGE_VERSION=$(git describe --tags --always)" >> $GITHUB_ENV
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push simple-nginx-proxy 
        uses: docker/build-push-action@v4
        with:
          context: ./containers/simple-nginx-proxy
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.CONTAINER_REGISTRY }}/gihyodocker/simple-nginx-proxy:${{ env.IMAGE_VERSION }}
      - name: Build and push debug 
        uses: docker/build-push-action@v4
        with:
          context: ./containers/debug
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.CONTAINER_REGISTRY }}/gihyodocker/debug:${{ env.IMAGE_VERSION }}
      - name: Build and push time-limit-job 
        uses: docker/build-push-action@v4
        with:
          context: ./containers/time-limit-job
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.CONTAINER_REGISTRY }}/gihyodocker/time-limit-job:${{ env.IMAGE_VERSION }}
